import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL!; const SERVICE=process.env.SUPABASE_SERVICE_ROLE_KEY!; const ANON=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||SERVICE;
const db=createClient(URL,SERVICE,{auth:{autoRefreshToken:false,persistSession:false}});
const out=(d:unknown,s=200)=>NextResponse.json(d,{status:s,headers:{"Cache-Control":"no-store"}});
async function adminUser(req:NextRequest){const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))return null;const token=h.slice(7);const c=createClient(URL,ANON,{auth:{autoRefreshToken:false,persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}});const a=await c.auth.getUser(token);if(a.error||!a.data.user)return null;const p=await db.from("usuarios").select("id").eq("auth_user_id",a.data.user.id).maybeSingle();if(!p.data)return null;const r=await db.from("usuarios_asignaciones").select("roles:rol_id(codigo,nombre)").eq("usuario_id",p.data.id).eq("activo",true);const ok=(r.data??[]).some((x:any)=>["ADMIN","ADMINISTRADOR","SUPERADMIN","SUPER_ADMIN"].includes(String(x.roles?.codigo??x.roles?.nombre).toUpperCase()));return ok?p.data.id:null;}
export async function GET(req:NextRequest){try{if(!await adminUser(req))return out({success:false,error:"No autorizado."},403);const r=await db.from("anuncios").select("id,titulo,contenido,activo,autor_id,created_at").order("created_at",{ascending:false});if(r.error)throw r.error;return out({success:true,anuncios:r.data??[]});}catch(e:any){return out({success:false,error:e?.message??"Error al listar anuncios."},500);}}
export async function POST(req:NextRequest){try{const uid=await adminUser(req);if(!uid)return out({success:false,error:"No autorizado."},403);const b=await req.json();const titulo=String(b.titulo??"").trim(),contenido=String(b.contenido??"").trim();if(!titulo||!contenido)return out({success:false,error:"Título y contenido son obligatorios."},400);const r=await db.from("anuncios").insert({titulo,contenido,activo:b.activo!==false,autor_id:uid}).select("id,titulo,contenido,activo,autor_id,created_at").single();if(r.error)throw r.error;return out({success:true,anuncio:r.data},201);}catch(e:any){return out({success:false,error:e?.message??"Error al crear anuncio."},500);}}
export async function PATCH(req:NextRequest){try{if(!await adminUser(req))return out({success:false,error:"No autorizado."},403);const b=await req.json();if(!b.id)return out({success:false,error:"ID requerido."},400);const u:any={};if(b.titulo!==undefined)u.titulo=String(b.titulo).trim();if(b.contenido!==undefined)u.contenido=String(b.contenido).trim();if(b.activo!==undefined)u.activo=Boolean(b.activo);const r=await db.from("anuncios").update(u).eq("id",b.id).select("id,titulo,contenido,activo,autor_id,created_at").single();if(r.error)throw r.error;return out({success:true,anuncio:r.data});}catch(e:any){return out({success:false,error:e?.message??"Error al actualizar anuncio."},500);}}
export async function DELETE(req:NextRequest){try{if(!await adminUser(req))return out({success:false,error:"No autorizado."},403);const id=req.nextUrl.searchParams.get("id");if(!id)return out({success:false,error:"ID requerido."},400);const r=await db.from("anuncios").delete().eq("id",id);if(r.error)throw r.error;return out({success:true});}catch(e:any){return out({success:false,error:e?.message??"Error al eliminar anuncio."},500);}}
